# Exercise 1: Testing Transactions and Cursor Queries in PostgreSQL

In [1]:
%%capture
import psycopg2

# Create a connection helper function for transaction testing
def get_connection():
    """Create a new PostgreSQL connection with autocommit disabled for transaction support"""
    conn = psycopg2.connect(
        dbname='postgres',
        user='postgres',
        password='postgres',
        host='127.0.0.1',
        port='5432'
    )
    conn.autocommit = False  # Required for transaction support
    return conn

# For simple queries, we'll use JupySQL
%config SqlMagic.autopandas = True;
%config SqlMagic.feedback = False;
%config SqlMagic.displaycon = False;
%load_ext sql
%sql postgresql://postgres:postgres@127.0.0.1:5432/postgres

In [2]:
%%sql
-- Drop all tables if they exist (to start fresh)
DROP TABLE IF EXISTS Accounts CASCADE;
DROP TABLE IF EXISTS Customers CASCADE;

""


#### Task 1: Create a table Customers with column customer_id, full_name, and email. The column types should be VARCHAR. Set primary the key.  

In [3]:
%%sql
BEGIN;
DROP TABLE IF EXISTS Accounts;
DROP TABLE IF EXISTS Customers;
CREATE TABLE Customers (
    customer_id INT PRIMARY KEY,
    full_name   VARCHAR(100) NOT NULL,
    email       VARCHAR(100) NOT NULL UNIQUE
);
COMMIT;

""


In [4]:
%%sql
BEGIN;

/*
 * A table for bank accounts.
 * We want to ensure that an account balance can NEVER be negative.
 * We also link each account to a valid customer.
 */

CREATE TABLE Accounts (
    account_id  INT PRIMARY KEY,
    customer_id INT NOT NULL,
    balance     DECIMAL(10, 2) NOT NULL CHECK (balance >= 0),
    
    -- This is the "link" that ensures an account belongs to a real customer
    CONSTRAINT fk_customer
        FOREIGN KEY(customer_id) 
        REFERENCES Customers(customer_id)
);
COMMIT;

""


In [5]:
%%sql
BEGIN;
-- Let's add some starting data
INSERT INTO Customers (customer_id, full_name, email) VALUES
(1, 'Alice Smith', 'alice@example.com'),
(2, 'Bob Johnson', 'bob@example.com');

INSERT INTO Accounts (account_id, customer_id, balance) VALUES
(101, 1, 1000.00),  -- Alice's account
(102, 2, 250.00);   -- Bob's account

COMMIT;


""


#### Task 2: Try to insert Charlie Brown into the table, with customer_id 3. Use the format Values(customer_id, full_name) for the actual record

In [6]:
%%sql
BEGIN;
INSERT INTO Customers (customer_id, full_name) 
VALUES (3, 'Charlie Brown');

RuntimeError: (psycopg2.errors.NotNullViolation) null value in column "email" of relation "customers" violates not-null constraint
DETAIL:  Failing row contains (3, Charlie Brown, null).

[SQL: INSERT INTO Customers (customer_id, full_name)
VALUES (3, 'Charlie Brown');]
(Background on this error at: https://sqlalche.me/e/20/gkpj)


In [7]:
%%sql
ROLLBACK;

""


#### Task 3: Try to insert Eve Davis into the table, with customer_id 4, and email alice@example.com. Use the format Values(customer_id, full_name, email) for the actual record

In [8]:
%%sql
BEGIN;
INSERT INTO Customers (customer_id, full_name, email) 
VALUES (4, 'Eve Davis', 'alice@example.com');

RuntimeError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "customers_email_key"
DETAIL:  Key (email)=(alice@example.com) already exists.

[SQL: INSERT INTO Customers (customer_id, full_name, email)
VALUES (4, 'Eve Davis', 'alice@example.com');]
(Background on this error at: https://sqlalche.me/e/20/gkpj)


In [9]:
%%sql
ROLLBACK;

""


#### Task 4: Try to set the balance of customer with accound_id 101 to -50. Complete the query below.

In [10]:
%%sql
BEGIN;
UPDATE Accounts 
SET balance = -50.00 
WHERE account_id = 101;

RuntimeError: (psycopg2.errors.CheckViolation) new row for relation "accounts" violates check constraint "accounts_balance_check"
DETAIL:  Failing row contains (101, 1, -50.00).

[SQL: UPDATE Accounts
SET balance = -50.00
WHERE account_id = 101;]
(Background on this error at: https://sqlalche.me/e/20/gkpj)


In [11]:
%%sql
ROLLBACK;

""


In [12]:
%%sql
BEGIN;
INSERT INTO Accounts (account_id, customer_id, balance) 
VALUES (103, 999, 50.00);



RuntimeError: (psycopg2.errors.ForeignKeyViolation) insert or update on table "accounts" violates foreign key constraint "fk_customer"
DETAIL:  Key (customer_id)=(999) is not present in table "customers".

[SQL: INSERT INTO Accounts (account_id, customer_id, balance)
VALUES (103, 999, 50.00);]
(Background on this error at: https://sqlalche.me/e/20/gkpj)


In [13]:
%%sql
ROLLBACK;

""


In [14]:
%%sql
SELECT * FROM Customers;

,customer_id,full_name,email
0,1,Alice Smith,alice@example.com
1,2,Bob Johnson,bob@example.com


In [15]:
conn = get_connection()
cursor = conn.cursor()

try:
    # Step 1: Subtract $100 from Alice
    cursor.execute("UPDATE Accounts SET balance = balance - 100.00 WHERE account_id = 101;")
    
    # Step 2: Add $100 to Bob
    cursor.execute("UPDATE Accounts SET balance = balance + 100.00 WHERE account_id = 102;")
    
    conn.commit()  # Finalize the transaction

    print("Transaction committed: Transfer successful")
    
except Exception as e:
    conn.rollback()
    print(f"Transaction rolled back: {e}")
    
finally:
    cursor.close()
    conn.close()

Transaction committed: Transfer successful


In [16]:
%%sql
SELECT * FROM Accounts;

,account_id,customer_id,balance
0,101,1,900.00
1,102,2,350.00


Expected Result: Alice will have 900.00 dollars and Bob will have 350.00.

#### Task 5: Set the addition and subtraction values of the balance query to balance - 5000 and balance + 5000.

In [17]:
conn = get_connection()
cursor = conn.cursor()

try:
    # Step 1: Subtract $5000 from Alice (This will fail the CHECK constraint)
    cursor.execute("UPDATE Accounts SET balance = balance - 5000.00 WHERE account_id = 101;")
    
    # Step 2: Add $5000 to Bob (This line may not even be reached)
    cursor.execute("UPDATE Accounts SET balance = balance + 5000.00 WHERE account_id = 102;")
    

    conn.commit()  # Try to finalize
    print("Transaction committed")
    
except Exception as e:
    conn.rollback()
    print(f"Transaction rolled back: {e}")
    
finally:
    cursor.close()
    conn.close()

Transaction rolled back: new row for relation "accounts" violates check constraint "accounts_balance_check"
DETAIL:  Failing row contains (101, 1, -4100.00).



In [18]:
# Session 1: Start a transaction and update Alice's balance (but don't commit yet)
conn1 = get_connection()
cursor1 = conn1.cursor()


# Begin transaction and update# Keep connection open for next cells (don't close yet!)

cursor1.execute("UPDATE Accounts SET balance = 50.00 WHERE account_id = 101;")
# Check the balance within this transactionresult = cursor1.fetchone()
cursor1.execute("SELECT balance FROM Accounts WHERE account_id = 101;")
rows = cursor1.fetchall()
print("Query results:")
for row in rows:
    print(row)
        

Query results:
(Decimal('50.00'),)


In [19]:
# Session 2: Open a separate connection to see if it can see uncommitted changes
conn2 = get_connection()
cursor2 = conn2.cursor()

cursor2.execute("SELECT balance FROM Accounts WHERE account_id = 101;")
rows = cursor2.fetchall()
print("Expected: $900.00 (Session 2 cannot see uncommitted changes from Session 1)")
print(f"Session 2 sees (before commit): ${rows[0][0]}")

Expected: $900.00 (Session 2 cannot see uncommitted changes from Session 1)
Session 2 sees (before commit): $900.00


#### Task 6: Commit the transaction using conn1.commit(). Close the connection and the cursor using the .close() functionality

In [20]:
# Session 1: Now commit the transaction
conn1.commit()

print("Session 1 transaction committed")
conn1.close()
cursor1.close()

Session 1 transaction committed


In [21]:
# Session 2: Open another connection to verify committed changes are now visible
conn2.close()
cursor2.close()

conn2 = get_connection()
cursor2 = conn2.cursor()

cursor2.execute("SELECT balance FROM Accounts WHERE account_id = 101;")
result = cursor2.fetchone()
print("Expected: $50.00 (Session 2 can now see committed changes from Session 1)")
print(f"Session 2 sees (after commit): ${result[0]}")

Expected: $50.00 (Session 2 can now see committed changes from Session 1)
Session 2 sees (after commit): $50.00


In [22]:
%%sql
SELECT * FROM Accounts
JOIN Customers ON Accounts.customer_id = Customers.customer_id;

,account_id,customer_id,balance,customer_id,full_name,email
0,102,2,350.00,2,Bob Johnson,bob@example.com
1,101,1,50.00,1,Alice Smith,alice@example.com


In [23]:
conn = get_connection()
cursor = conn.cursor()

try:
    cursor.execute("UPDATE Accounts SET balance = balance + 77.00 WHERE account_id = 102;")    
    conn.commit()    
    
    print("Transaction committed: Bob received $77.00 bonus")

except Exception as e:    
    print(f"Transaction rolled back: {e}")
    conn.rollback()
    
finally:
    cursor.close()
    conn.close()

Transaction committed: Bob received $77.00 bonus


Let's make sure the data is all there. We should see Bob's new balance, with his increased bonus.


In [24]:
%%sql
SELECT balance FROM Accounts WHERE account_id = 102;

,balance
0,427.00


#### Task 7: Open another connection called new_conn, and set the cursor to new_conn.cursor().

In [25]:
new_conn = get_connection()
cursor = new_conn.cursor()

try:
    cursor.execute("SELECT * FROM Accounts JOIN Customers ON Accounts.customer_id = Customers.customer_id WHERE account_id = 102;")    
    new_conn.commit()    
    
    print("Transaction is durable: Bob still has the same balance after reconnecting")

    result = cursor.fetchone()
    print(f"${result}")

except Exception as e:    
    print(f"Transaction rolled back: {e}")
    new_conn.rollback()
    
finally:
    cursor.close()
    new_conn.close()

Transaction is durable: Bob still has the same balance after reconnecting
$(102, 2, Decimal('427.00'), 2, 'Bob Johnson', 'bob@example.com')
