# Exercise 1: Querying MongoDB - Document Stores vs Relational Databases

In Lesson 2, we explored JSONB support in PostgreSQL for flexible data. In this session, we take that idea to a new level: **the entire database is flexible**. 

MongoDB is a document-oriented database that stores data in JSON-like documents. It was created to solve specific problems that relational databases struggle with:
- **Horizontal scaling** across multiple servers
- **Flexible schemas** that can evolve without migrations
- **Nested data** that doesn't require complex joins

However, this flexibility comes with trade-offs. In this exercise, you'll:
1. Query documents in MongoDB
2. Compare joins and aggregations between MongoDB and PostgreSQL
3. Explore the benefits and challenges of schema flexibility

## Step 1: Setting Up MongoDB and PostgreSQL Connections

We'll use PyMongo to connect to MongoDB and JupySQL for PostgreSQL. This lets us compare the same operations in both systems.

(Run this code block to set up connections)

In [ ]:
%%capture
%pip install pymongo psycopg2 jupysql pandas;
import pymongo
from pymongo import MongoClient
import pandas as pd
import time

# Connect to MongoDB
mongo_client = MongoClient('mongodb://localhost:27017/')
db = mongo_client['ecommerce_db']

# For PostgreSQL queries
%config SqlMagic.autopandas = True;
%config SqlMagic.feedback = False;
%config SqlMagic.displaycon = False;
%load_ext sql
%sql postgresql://postgres:postgres@127.0.0.1:5432/postgres

print("✅ Connected to MongoDB and PostgreSQL")

In [ ]:
# Drop MongoDB collections if they exist (to start fresh)
db.orders.drop()
db.customers.drop()

# Drop PostgreSQL tables if they exist
%sql DROP TABLE IF EXISTS Orders CASCADE;
%sql DROP TABLE IF EXISTS Customers CASCADE;

## Step 2: Loading Sample Data

Let's create an e-commerce scenario with customers and their orders. We'll load the same data into both MongoDB and PostgreSQL to compare them.

### MongoDB: Documents with Nested Data

In MongoDB, we can store all related information together in a single document. An order can contain customer information embedded within it.

In [ ]:
# Clear existing data
db.orders.drop()
db.customers.drop()

# MongoDB: Insert customer documents
customers_collection = db.customers
customers = [
    {"customer_id": 1, "name": "Alice Smith", "email": "alice@example.com", "state": "CA"},
    {"customer_id": 2, "name": "Bob Johnson", "email": "bob@example.com", "state": "NY"},
    {"customer_id": 3, "name": "Charlie Day", "email": "charlie@example.com", "state": "PA"}
]
customers_collection.insert_many(customers)

# MongoDB: Insert order documents with embedded customer info
orders_collection = db.orders
orders = [
    {
        "order_id": 101,
        "customer_id": 1,
        "customer_name": "Alice Smith",  # Denormalized!
        "product": "Laptop",
        "quantity": 1,
        "total": 1200.00,
        "order_date": "2024-01-15"
    },
    {
        "order_id": 102,
        "customer_id": 2,
        "customer_name": "Bob Johnson",
        "product": "Mouse",
        "quantity": 2,
        "total": 50.00,
        "order_date": "2024-01-16"
    },
    {
        "order_id": 103,
        "customer_id": 1,
        "customer_name": "Alice Smith",
        "product": "Keyboard",
        "quantity": 1,
        "total": 75.00,
        "order_date": "2024-01-17"
    },
    {
        "order_id": 104,
        "customer_id": 3,
        "customer_name": "Charlie Day",
        "product": "Monitor",
        "quantity": 1,
        "total": 300.00,
        "order_date": "2024-01-18"
    }
]
orders_collection.insert_many(orders)

print(f"✅ Inserted {customers_collection.count_documents({})} customers")
print(f"✅ Inserted {orders_collection.count_documents({})} orders")

""


### PostgreSQL: Normalized Relational Tables

In PostgreSQL, we normalize the data: customers and orders are separate tables linked by foreign keys.

In [ ]:
%%sql
BEGIN;
DROP TABLE IF EXISTS Orders;
DROP TABLE IF EXISTS Customers;

CREATE TABLE Customers (
    customer_id INT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    state VARCHAR(50)
);

CREATE TABLE Orders (
    order_id INT PRIMARY KEY,
    customer_id INT NOT NULL,
    product VARCHAR(100) NOT NULL,
    quantity INT NOT NULL,
    total DECIMAL(10, 2) NOT NULL,
    order_date DATE NOT NULL,
    FOREIGN KEY (customer_id) REFERENCES Customers(customer_id)
);

INSERT INTO Customers (customer_id, name, email, state) VALUES
(1, 'Alice Smith', 'alice@example.com', 'CA'),
(2, 'Bob Johnson', 'bob@example.com', 'NY'),
(3, 'Charlie Day', 'charlie@example.com', 'PA');

INSERT INTO Orders (order_id, customer_id, product, quantity, total, order_date) VALUES
(101, 1, 'Laptop', 1, 1200.00, '2024-01-15'),
(102, 2, 'Mouse', 2, 50.00, '2024-01-16'),
(103, 1, 'Keyboard', 1, 75.00, '2024-01-17'),
(104, 3, 'Monitor', 1, 300.00, '2024-01-18');

COMMIT;

""


## Step 3: Simple Queries - Reading Documents

Let's start with basic queries in both systems.

### MongoDB: Find all orders

In [ ]:
# MongoDB query
orders = list(db.orders.find())
pd.DataFrame(orders)

""


Notice: MongoDB returns documents with all fields, including the embedded `customer_name`. We get related data without a JOIN!

### PostgreSQL: Select all orders

%%sql
SELECT * FROM Orders;

In [ ]:
Notice: PostgreSQL only shows order data. To get customer names, we need a JOIN.

## Step 4: Filtering Data

### MongoDB: Find orders over $100

(Fill in the blank to query orders where total is greater than 100)

RuntimeError: (psycopg2.errors.NotNullViolation) null value in column "email" of relation "customers" violates not-null constraint
DETAIL:  Failing row contains (3, Charlie Brown, null).

[SQL: INSERT INTO Customers (customer_id, full_name)
VALUES (3, 'Charlie Brown');]
(Background on this error at: https://sqlalche.me/e/20/gkpj)


# MongoDB uses query documents with operators like $gt (greater than)
expensive_orders = list(db.orders.find({"total": {"$gt": 100}}))  # ??? - Use $gt operator
pd.DataFrame(expensive_orders)

In [ ]:
### PostgreSQL: Find orders over $100

""


%%sql
SELECT * FROM Orders WHERE total > 100;

In [ ]:
## Step 5: The JOIN Problem - Where MongoDB Struggles

Now for the critical comparison: **What if we need to get customer details along with orders?**

In PostgreSQL, this is straightforward with a JOIN. In MongoDB, we have two options:
1. **Embed data** (denormalize) - fast but creates redundancy
2. **Use $lookup** (MongoDB's "join") - slower and less efficient

### PostgreSQL: Fast JOIN

RuntimeError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "customers_email_key"
DETAIL:  Key (email)=(alice@example.com) already exists.

[SQL: INSERT INTO Customers (customer_id, full_name, email)
VALUES (4, 'Eve Davis', 'alice@example.com');]
(Background on this error at: https://sqlalche.me/e/20/gkpj)


%%time
%%sql
SELECT 
    o.order_id,
    o.product,
    o.total,
    c.name,
    c.email,
    c.state
FROM Orders o
JOIN Customers c ON o.customer_id = c.customer_id
ORDER BY o.order_id;

In [ ]:
✅ PostgreSQL performs this JOIN very efficiently. Relational databases are optimized for this!

### MongoDB: $lookup (Aggregation Pipeline)

MongoDB doesn't have traditional JOINs. Instead, we use the aggregation framework with `$lookup`.

(Fill in the blanks to complete the lookup)

""


%%time
# MongoDB $lookup to "join" orders with customers
pipeline = [
    {
        "$lookup": {
            "from": "customers",           # ??? - The collection to join with
            "localField": "customer_id",   # ??? - Field from orders collection
            "foreignField": "customer_id", # ??? - Field from customers collection
            "as": "customer_info"          # ??? - Output array field name
        }
    },
    {
        "$unwind": "$customer_info"  # Flatten the array
    },
    {
        "$project": {  # Select fields to display
            "order_id": 1,
            "product": 1,
            "total": 1,
            "customer_name": "$customer_info.name",
            "email": "$customer_info.email",
            "state": "$customer_info.state"
        }
    }
]

results = list(db.orders.aggregate(pipeline))
pd.DataFrame(results)

In [ ]:
⚠️ **Performance Note:** MongoDB's `$lookup` is significantly slower than PostgreSQL's JOIN, especially with large datasets. This is why MongoDB encourages **embedding data** (denormalization) instead of joining.

**Lesson:** MongoDB wasn't designed for complex joins. It's optimized for reading complete documents quickly, not for joining normalized data across collections.

## Step 6: Aggregation - Where MongoDB Shines

Now let's calculate total sales per customer. This requires grouping and aggregating data.

### PostgreSQL: GROUP BY

RuntimeError: (psycopg2.errors.CheckViolation) new row for relation "accounts" violates check constraint "accounts_balance_check"
DETAIL:  Failing row contains (101, 1, -50.00).

[SQL: UPDATE Accounts
SET balance = -50.00
WHERE account_id = 101;]
(Background on this error at: https://sqlalche.me/e/20/gkpj)


%%sql
SELECT 
    c.name,
    COUNT(o.order_id) AS num_orders,
    SUM(o.total) AS total_spent
FROM Customers c
JOIN Orders o ON c.customer_id = o.customer_id
GROUP BY c.name
ORDER BY total_spent DESC;

In [ ]:
### MongoDB: Aggregation Pipeline

MongoDB's aggregation framework is powerful for these operations.

(Fill in the blank for the $sum operation)

""


# MongoDB aggregation
pipeline = [
    {
        "$group": {
            "_id": "$customer_name",
            "num_orders": {"$sum": 1},         # Count documents
            "total_spent": {"$sum": "$total"}  # ??? - Sum the total field
        }
    },
    {
        "$sort": {"total_spent": -1}  # Sort descending
    }
]

results = list(db.orders.aggregate(pipeline))
pd.DataFrame(results)

In [ ]:
Notice how MongoDB's aggregation works well because we **embedded the customer_name** in each order document. We didn't need to join!

## Step 7: Schema Flexibility - The Double-Edged Sword

MongoDB's flexibility is powerful, but it can lead to **data inconsistencies**.

### Scenario: Flexible Product Metadata

Let's add new orders with varying product attributes:

RuntimeError: (psycopg2.errors.ForeignKeyViolation) insert or update on table "accounts" violates foreign key constraint "fk_customer"
DETAIL:  Key (customer_id)=(999) is not present in table "customers".

[SQL: INSERT INTO Accounts (account_id, customer_id, balance)
VALUES (103, 999, 50.00);]
(Background on this error at: https://sqlalche.me/e/20/gkpj)


# In MongoDB, each document can have different fields!
flexible_orders = [
    {
        "order_id": 105,
        "customer_id": 2,
        "customer_name": "Bob Johnson",
        "product": "Webcam",
        "quantity": 1,
        "total": 89.00,
        "order_date": "2024-01-19",
        "warranty": "2 years"  # New field!
    },
    {
        "order_id": 106,
        "customer_id": 1,
        "customer_name": "Alice Smith",
        "product": "USB Cable",
        "quantity": 3,
        "total": 15.00,
        "order_date": "2024-01-20",
        "color": "black",      # Different field!
        "length_cm": 200       # Another different field!
    }
]

db.orders.insert_many(flexible_orders)
print("✅ Inserted orders with varying schemas")

# Query all orders
all_orders = list(db.orders.find())
pd.DataFrame(all_orders)

✅ **Benefit:** MongoDB accepts documents with different fields. No schema migration needed!

⚠️ **Problem:** Now we have **inconsistent data**. Some orders have warranties, some have colors, some have neither. This makes analysis difficult.

### The Schema Consistency Problem

Let's try to calculate average order value, but what if someone enters a string instead of a number?

In [ ]:
# Someone makes a data entry mistake
bad_order = {
    "order_id": 107,
    "customer_id": 3,
    "customer_name": "Charlie Day",
    "product": "Headphones",
    "quantity": "one",      # ❌ String instead of number!
    "total": "ninety-nine", # ❌ String instead of number!
    "order_date": "2024-01-21"
}

db.orders.insert_one(bad_order)
print("⚠️ Inserted order with wrong data types - MongoDB accepted it!")

c:\Users\ktoto\AppData\Local\Programs\Python\Python313\Lib\site-packages\sql\connection\connection.py:881: JupySQLRollbackPerformed: Current transaction is aborted. JupySQL executed a ROLLBACK operation.
  warnings.warn(
RuntimeError: (psycopg2.errors.InFailedSqlTransaction) current transaction is aborted, commands ignored until end of transaction block

[SQL: SELECT * FROM Customers;]
(Background on this error at: https://sqlalche.me/e/20/2j85)


Now try to aggregate total sales:

In [ ]:
# Try to calculate total revenue
try:
    pipeline = [
        {
            "$group": {
                "_id": None,
                "total_revenue": {"$sum": "$total"}
            }
        }
    ]
    result = list(db.orders.aggregate(pipeline))
    print(f"Total Revenue: {result}")
except Exception as e:
    print(f"❌ Error: {e}")
    
# The aggregation might succeed but give incorrect results!
# Let's check what order 107 looks like:
bad_order_check = db.orders.find_one({"order_id": 107})
print(f"\nOrder 107 data: {bad_order_check}")
print(f"Type of 'total': {type(bad_order_check['total'])}")

""


**Problem:** MongoDB accepted invalid data types! The `$sum` operation skipped the string, giving us **incorrect results** without a clear error.

### PostgreSQL Would Reject This

Let's try the same mistake in PostgreSQL:

In [ ]:
%%sql
BEGIN;
INSERT INTO Orders (order_id, customer_id, product, quantity, total, order_date)
VALUES (107, 3, 'Headphones', 'one', 'ninety-nine', '2024-01-21');
COMMIT;

,customer_id,full_name,email
0,1,Alice Smith,alice@example.com
1,2,Bob Johnson,bob@example.com


🛑 **PostgreSQL rejects this with a type error!** The schema enforces data integrity.

## Step 8: When to Use MongoDB vs PostgreSQL

### Use MongoDB When:
✅ Schema changes frequently and unpredictably
✅ Data is naturally nested (e.g., blog posts with comments)
✅ You need horizontal scaling across many servers
✅ Most queries read complete documents (no complex joins)
✅ You need fast writes and reads for simple queries

### Use PostgreSQL When:
✅ Data relationships are complex and require many joins
✅ Data integrity and consistency are critical (financial data, etc.)
✅ Schema is well-defined and stable
✅ You need ACID transactions across multiple tables
✅ Business intelligence and precise calculations are required

### The Hybrid Approach:
Many modern applications use **both**:
- PostgreSQL for core transactional data (orders, payments, users)
- MongoDB for flexible data (product catalogs, user preferences, logs)

In [ ]:
## Key Takeaways

**MongoDB Strengths:**
- Fast reads for complete documents
- Flexible schemas that evolve without migrations
- Horizontal scaling for massive datasets
- Great for rapid prototyping

**MongoDB Weaknesses:**
- Joins ($lookup) are slow and inefficient
- No schema enforcement can lead to data quality issues
- Harder to ensure data consistency
- Not ideal for complex relational queries

**PostgreSQL Strengths:**
- Excellent JOIN performance
- Strong data consistency and type checking
- ACID transactions
- Perfect for complex queries and business intelligence

**PostgreSQL Weaknesses:**
- Schema changes require migrations
- Vertical scaling has limits
- Less flexible for rapidly evolving data models

**The Bottom Line:** Choose your database based on your data's **nature** and **access patterns**, not trends or popularity.

✅ Transaction committed: Transfer successful


Expected Result: ✅ Success. Alice will have 900.00 dollars and Bob will have 350.00. Both updates worked, so the COMMIT made them permanent.

Let's move onto the "Failure Path" i.e. an Atomic Rollback. Start with a transfer $5,000 from Alice to Bob. Alice only has $900. The CHECK constraint will stop this.

#### Task 5: Set the addition and subtraction values of the balance query to balance - 5000 and balance + 5000.

In [ ]:
conn = get_connection()
cursor = conn.cursor()

try:
    # Step 1: Subtract $5000 from Alice (This will fail the CHECK constraint)
    cursor.execute("UPDATE Accounts SET balance = balance - 5000.00 WHERE account_id = 101;")
    
    # Step 2: Add $5000 to Bob (This line may not even be reached)
    cursor.execute("UPDATE Accounts SET balance = balance + 5000.00 WHERE account_id = 102;")
    

    conn.commit()  # Try to finalize
    print("Transaction committed")
    
except Exception as e:
    conn.rollback()
    print(f"Transaction rolled back: {e}")
    
finally:
    cursor.close()
    conn.close()

❌ Transaction rolled back: new row for relation "accounts" violates check constraint "accounts_balance_check"
DETAIL:  Failing row contains (101, 1, -4100.00).



Expected Result: Failure. The database will throw a CHECK constraint error (from Exercise 1C) when it tries to execute the first UPDATE. The COMMIT will fail and/or you'll be forced to ROLLBACK. 
In general, we will ROLLBACK regardless, as it's good practice to do so after a transaction has failed. 

Let's see if this failed correctly - i.e. that both transactions failed, not just one. 

In [18]:
%%sql
SELECT * FROM Accounts;

,account_id,customer_id,balance
0,101,1,900.00
1,102,2,350.00


You will see that Alice still has 900.00 dollars and Bob still has 350.00. Crucially, Bob did not get $5000, and Alice's account was not set to a negative value. Because one part of the transaction failed (Step 1), the entire transaction was aborted. This is Atomicity.

### Part 3: Testing 'I' (Isolation)
We've shown the database can guarantee Atomicity, and Consistency. Next, we want to show that one transaction doesn't see the "dirty" or uncommitted work of another. This requires two separate database connections - which we can simulate by using multiple notebook cells with %sql magic, where each transaction is kept open until explicitly committed or rolled back.

Here's the starting Point: Alice (101) has $900.00.

In Session 1 (First Cell) we will:
1. Run BEGIN TRANSACTION;	
2. Run UPDATE Accounts SET balance = 50.00 WHERE account_id = 101; (Alice's new balance is $50, but don't COMMIT!)	
3. Check the balance: SELECT balance FROM Accounts WHERE account_id = 101; 

You should see the balance is 50.00 dollars within this transaction.

NEXT - 

4. In a separate cell (Session 2), open a new connection and check the balance: SELECT balance FROM Accounts WHERE account_id = 101;
Expected Result: Session 2 sees **900.00** dollars. It does not see the uncommitted 50.00 dollar value. It is isolated from Session 1's incomplete work.
5. Back in Session 1, run: COMMIT;	
6. Immediately after Session 1 commits, run this again in Session 2: SELECT balance FROM Accounts WHERE account_id = 101;
Expected Result: Now Session 2 sees **$50.00**. It can only see the new value after it has been fully and durably committed.

As you can see, isolation prevents other connections from reading "dirty" or "in-progress" data, which would lead to massive confusion and inconsistency.

In [19]:
# Session 1: Start a transaction and update Alice's balance (but don't commit yet)
conn1 = get_connection()
cursor1 = conn1.cursor()


# Begin transaction and update# Keep connection open for next cells (don't close yet!)

cursor1.execute("UPDATE Accounts SET balance = 50.00 WHERE account_id = 101;")
# Check the balance within this transactionresult = cursor1.fetchone()
cursor1.execute("SELECT balance FROM Accounts WHERE account_id = 101;")
rows = cursor1.fetchall()
print("Query results:")
for row in rows:
    print(row)
        

Query results:
(Decimal('50.00'),)


In [20]:
# Session 2: Open a separate connection to see if it can see uncommitted changes
conn2 = get_connection()
cursor2 = conn2.cursor()

cursor2.execute("SELECT balance FROM Accounts WHERE account_id = 101;")
rows = cursor2.fetchall()
print("Expected: $900.00 (Session 2 cannot see uncommitted changes from Session 1)")
print(f"Session 2 sees (before commit): ${rows[0][0]}")

Expected: $900.00 (Session 2 cannot see uncommitted changes from Session 1)
Session 2 sees (before commit): $900.00


#### Task 6: Commit the transaction using conn1.commit(). Close the connection and the cursor using the .close() functionality

In [ ]:
# Session 1: Now commit the transaction
conn1.commit()

print("Session 1 transaction committed")
conn1.close()
cursor1.close()

✅ Session 1 transaction committed


In [22]:
# Session 2: Open another connection to verify committed changes are now visible
conn2.close()
cursor2.close()

conn2 = get_connection()
cursor2 = conn2.cursor()

cursor2.execute("SELECT balance FROM Accounts WHERE account_id = 101;")
result = cursor2.fetchone()
print("Expected: $50.00 (Session 2 can now see committed changes from Session 1)")
print(f"Session 2 sees (after commit): ${result[0]}")

Expected: $50.00 (Session 2 can now see committed changes from Session 1)
Session 2 sees (after commit): $50.00


Which is exactly what we expected! The isolation property works perfectly.

So far, we have the ACI - Atomicity, Consistency, and Isolation gaurantees of the database tested. Let's add the D in ACID. 

### Part 4: Testing 'D' (Durability)
We need to show that once COMMIT is executed, the data is safe and permanent. In most terms, this usually means it's stored on disk and not volatile memory. Let's give Bob a $77.00 bonus. Before we do that, let's see what is currently in the accounts:


In [23]:
%%sql
SELECT * FROM Accounts
JOIN Customers ON Accounts.customer_id = Customers.customer_id;

,account_id,customer_id,balance,customer_id,full_name,email
0,102,2,350.00,2,Bob Johnson,bob@example.com
1,101,1,50.00,1,Alice Smith,alice@example.com


In [ ]:
conn = get_connection()
cursor = conn.cursor()

try:
    cursor.execute("UPDATE Accounts SET balance = balance + 77.00 WHERE account_id = 102;")    
    conn.commit()    
    
    print("Transaction committed: Bob received $77.00 bonus")

except Exception as e:    
    print(f"Transaction rolled back: {e}")
    conn.rollback()
    
finally:
    cursor.close()
    conn.close()

✅ Transaction committed: Bob received $77.00 bonus


Let's make sure the data is all there. We should see Bob's new balance, with his increased bonus.


In [25]:
%%sql
SELECT balance FROM Accounts WHERE account_id = 102;

,balance
0,427.00


Here comes the test: Now, we'll simulate a database restart by creating a fresh connection in the next cell. This demonstrates durability - that committed data survives even after connections are closed.

#### Task 7: Open another connection called new_conn, and set the cursor to new_conn.cursor().

In [ ]:
new_conn = get_connection()
cursor = new_conn.cursor()

try:
    cursor.execute("SELECT * FROM Accounts JOIN Customers ON Accounts.customer_id = Customers.customer_id WHERE account_id = 102;")    
    new_conn.commit()    
    
    print("Transaction is durable: Bob still has the same balance after reconnecting")

    result = cursor.fetchone()
    print(f"${result}")

except Exception as e:    
    print(f"Transaction rolled back: {e}")
    new_conn.rollback()
    
finally:
    cursor.close()
    new_conn.close()

✅ Transaction is durable: Bob still has the same balance after reconnecting
$(102, 2, Decimal('427.00'), 2, 'Bob Johnson', 'bob@example.com')


Lesson: The value is still the same. Because the transaction was COMMITted, the database guarantees that this change is Durable and has survived the "crash" (i.e., you disconnecting). This is the opposite of ROLLBACK.