# Exercise 2: Data, Metadata & Query Engines

In this exercise, you'll compare how different database systems handle data and metadata. You'll observe performance differences and see how traditional databases bundle components versus how modern data catalogs separate them. To get started, imagine you have a dataset of product sales. Note, these could be any item: 

| transaction\_id | product\_id | sale\_date | quantity | price |
| :---: | :---: | :---: | :---: | :---: |
| 1 | 101 | 2025-10-14 | 5 | 19.99 |
| 2 | 102 | 2025-10-14 | 1 | 250.00 |
| 3 | 101 | 2026-01-30 | 3 | 19.99 |
| 4 | 103 | 2026-03-15 | 10 | 5.50 |
| 5 | 102 | 2026-10-16 | 2 | 245.00 |

We'll load this information into DuckDB, as well as PostgreSQL to start. Both DuckDB and PostgreSQL are end-to-end full databases. They provide the three main components we need to work with data (this is a simplified worldview, but bear with us):

- Storage
- Metadata 
- Query Engine

It's easy to see why storage matters. That's the core functionality of a database - to store data. Query engines also make intuitive sense at first glance - you have to be able to retrieve the data you've stored, otherwise what's the point? If you couldn't get the data back using standard SQL syntax, might as well send the data into a black hole. For that reason, we'll start our journey with these more familiar components - loading and data storage. Then, later we separate out all the pieces of the database to see what's really going on, and why metadata is also critical.


## Step 1: Data Loading, Storing & Querying

The following Python code snippets use DuckDB for an in-memory database and psycopg2/SQLAlchemy to connect to a running Postgres database.

### DuckDB:
First, as always, we'll import the libraries needed, and create the necessary sales table to insert data into. Simply run the cells below to get started. No modifications are required at this stage.  

In [1]:
%config SqlMagic.autopandas = True;
%config SqlMagic.feedback = False;
%config SqlMagic.displaycon = False;
import duckdb;
import pandas as pd
import pyarrow as pa
import zipfile;
import os;
from io import StringIO
from pyiceberg.catalog import load_catalog
from pyiceberg.schema import Schema
from pyiceberg.types import NestedField, IntegerType, StringType, FloatType
from pyiceberg.expressions import GreaterThan, EqualTo

%load_ext sql
conn = duckdb.connect();
%sql conn --alias duckdb
%sql duckdb:///exercise2.db

In [2]:
%%sql
-- Drop tables if they exist (to start fresh)
DROP TABLE IF EXISTS sales;

,Success


Next, let's create the table we need in DuckDB:

#### Task 1: Fill in the blank column names after the CREATE OR REPLACE TABLE portion of the DuckDB SQL statement to configure our initial table which aligns with the information above.

In [3]:
%%sql
CREATE OR REPLACE TABLE sales (
    transaction_id INTEGER,
    product_id INTEGER,
    --- BEGIN SOLUTION
    sale_date DATE,
    --- END SOLUTION
    quantity INTEGER,
    --- BEGIN SOLUTION
    price DOUBLE
    --- END SOLUTION
);

,Success


Now that the table structure is created using the DDL SQL statements above, we'll have to insert data using DML SQL code as per below. 

#### Task 2: Fill in the blank rows after the INSERT INTO ... VALUES portion of the DuckDB SQL statement to insert data which aligns with the table above.

In [4]:
%%timeit
%%sql
INSERT INTO sales (transaction_id, product_id, sale_date, quantity, price) VALUES
(1, 101, '2025-10-14', 5, 19.99),
(2, 102, '2025-10-14', 1, 250.00), 
--- BEGIN SOLUTION
(3, 101, '2026-01-30', 3, 19.99), 
(4, 103, '2026-03-15', 10, 5.50),
--- END SOLUTION
(5, 102, '2026-10-16', 2, 245.00);

12.7 ms ± 414 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


Let's quickly query the data to see if we have everything configured correctly. You should see five columns, but more than five rows. The reason for this is that we are using the %%timeit notebook magic. This command allows us to run the insert statement many times over. Using %%timeit, the system records how long each run of the insert statement takes, and the notebook reports the average (mean) time per loop, alongside a standard deviation (how much the insert statement runtimes typically varied). 

In [5]:
%%sql
SELECT * FROM sales;

,transaction_id,product_id,sale_date,quantity,price
0,1,101,2025-10-14,5,19.99
1,2,102,2025-10-14,1,250.00
2,3,101,2026-01-30,3,19.99
3,4,103,2026-03-15,10,5.50
4,5,102,2026-10-16,2,245.00
...,...,...,...,...,...
4050,1,101,2025-10-14,5,19.99
4051,2,102,2025-10-14,1,250.00
4052,3,101,2026-01-30,3,19.99
4053,4,103,2026-03-15,10,5.50


This concludes the DuckDB portion of our data insertion. Note that the insert statements took several milliseconds. While this is fast for human time standards, we can improve on this, as DuckDB is not designed for fast, simultaneous writes. We'll explore this later. 

## PostgreSQL
Moving onto PostgreSQL, we'll first configure our SQL connection using the notebook magic %sql command. This allows the jupysql package (loaded in this notebook) to set SQL code run after this cell to a PostgreSQL connection.

In [6]:
%sql postgresql://postgres:postgres@127.0.0.1:5432/postgres

Just as we did with DuckDB, at the next stage, we'll have to define a PostgreSQL equivalent of the table we used above using the appropriate DDL.

#### Task 3: Fill in the blanks after the CREATE TABLE ... portion of the SQL statement, to create columns in PostgreSQL which aligns (in terms of type and name) with the data above.

In [7]:
%%sql
-- Drop the sales table if it exists to start fresh
DROP TABLE IF EXISTS sales;
CREATE TABLE sales (
    transaction_id INTEGER,
    --- BEGIN SOLUTION
    product_id INTEGER,
    sale_date DATE,
    --- END SOLUTION
    quantity INTEGER,
    --- BEGIN SOLUTION
    price NUMERIC(10, 2) -- Use NUMERIC or DECIMAL for precise currency values
    --- END SOLUTION
)

""


Just as with the DuckDB portion of the exercise which we previously tested, here we will also have to insert records after the table is created using DML once again. In the PostgreSQL insert statement below, you will notice that we also use the %%timeit notebook magic. Just as before, this will run the insert statement several times, and time each operation. 

#### Task 4: Fill in the blank rows after the INSERT INTO ... VALUES portion of the PostgreSQL statement to insert data which aligns with the table above.

In [8]:
%%timeit
%%sql
INSERT INTO sales (transaction_id, product_id, sale_date, quantity, price) VALUES
--- BEGIN SOLUTION
(1, 101, '2025-10-14', 5, 19.99), 
(2, 102, '2025-10-14', 1, 250.00), 
(3, 101, '2026-01-30', 3, 19.99), 
(4, 103, '2026-03-15', 10, 5.50), 
(5, 102, '2026-10-16', 2, 245.00);
--- END SOLUTION

8.64 ms ± 968 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


Note that the two databases, PostgreSQL and DuckDB use slightly different SQL dialects, although they are very closely comparable. 

So now, we've inserted our data and effectively stored it in the database. DuckDB stores this data temporarily on volatile memory, unless we specify that it should save such data to disk (which is what we have done here). PostgreSQL works to store data on disk right away. This distinct difference occurs because DuckDB is an embedded database, designed to work within other processes, whereas PostgreSQL is designed to work as a database server software all on its own (which other technologies can then connect to). 

We can however, specify that DuckDB also write to disk using a "persistent" setting. Regardless, we can see that Postgres is slightly faster for loading the data: we will come back to this later, and explore this concept in the future.

Let's query the data just to see what's there:

In [9]:
%%sql
SELECT * FROM sales

,transaction_id,product_id,sale_date,quantity,price
0,1,101,2025-10-14,5,19.99
1,2,102,2025-10-14,1,250.00
2,3,101,2026-01-30,3,19.99
3,4,103,2026-03-15,10,5.50
4,5,102,2026-10-16,2,245.00
...,...,...,...,...,...
4050,1,101,2025-10-14,5,19.99
4051,2,102,2025-10-14,1,250.00
4052,3,101,2026-01-30,3,19.99
4053,4,103,2026-03-15,10,5.50


Congratulations! You have successfully queried and stored data using DML and DDL in both an OLAP and OLTP database system (DuckDB and PostgreSQL, respectively). Remember though - this course is not about just writing SQL. It's about learning what's under the hood. So we aren't quite done. There is a middle layer we have to investigate further - and that's the hidden hero of our story.   

## Part 2: Exploring Internal Metadata (The "Data about Data")
Let's think about this magical metadata layer - databases don't just store your data; they also store information about your data. This metadata is crucial for the query engine to work correctly. We're going to explore this later in the assignment, but let's begin with just an overview about what DuckDB and Postgres know by querying their internal "data catalogs" about our sales table.

### DuckDB Metadata Query:

In [10]:
%sql duckdb:///exercise2.db

In [11]:
%%sql
SELECT * FROM information_schema.columns WHERE table_name = 'sales';

,table_catalog,table_schema,table_name,column_name,ordinal_position,column_default,is_nullable,data_type,character_maximum_length,character_octet_length,...,identity_generation,identity_start,identity_increment,identity_maximum,identity_minimum,identity_cycle,is_generated,generation_expression,is_updatable,COLUMN_COMMENT
0,exercise2,main,sales,transaction_id,1,None,YES,INTEGER,<NA>,<NA>,...,None,None,None,None,None,<NA>,None,None,<NA>,None
1,exercise2,main,sales,product_id,2,None,YES,INTEGER,<NA>,<NA>,...,None,None,None,None,None,<NA>,None,None,<NA>,None
2,exercise2,main,sales,sale_date,3,None,YES,DATE,<NA>,<NA>,...,None,None,None,None,None,<NA>,None,None,<NA>,None
3,exercise2,main,sales,quantity,4,None,YES,INTEGER,<NA>,<NA>,...,None,None,None,None,None,<NA>,None,None,<NA>,None
4,exercise2,main,sales,price,5,None,YES,DOUBLE,<NA>,<NA>,...,None,None,None,None,None,<NA>,None,None,<NA>,None


### PostgreSQL Metadata Query

In [12]:
%sql postgresql://postgres:postgres@127.0.0.1:5432/postgres

In [13]:
%%sql
SELECT column_name, data_type
FROM information_schema.columns
WHERE table_name = 'sales';

,column_name,data_type
0,transaction_id,integer
1,product_id,integer
2,sale_date,date
3,quantity,integer
4,price,numeric


So, using metadata, the query engine of a database can see details about the types of data we're storing, and what is expected of the table as a whole. This prevents errors and other issues that can occur when working with the database in practice. The query engine typically checks the metadata before writing or reading information to prevent potential issues.

Let's make an adjustment to the tables and see how things change in the metadata returned by DuckDB and PostgreSQL. We'll add CustomerID, a string, but it will be empty for now.

#### Task 5: Alter the columns in both DuckDB and PostgreSQL using the appropriate DDL to add customer ID as a blank column - and then re-run the selected queries
First, let's alter the DuckDB table

In [14]:
%sql duckdb:///exercise2.db

In [15]:
%%sql
ALTER TABLE 
sales 
ADD COLUMN 
--- BEGIN SOLUTION
customer_id VARCHAR;
--- END SOLUTION

,Success


Now let's check the DuckDB metadata again to see the new column:

In [16]:
%%sql
SELECT * FROM information_schema.columns WHERE table_name = 'sales';

,table_catalog,table_schema,table_name,column_name,ordinal_position,column_default,is_nullable,data_type,character_maximum_length,character_octet_length,...,identity_generation,identity_start,identity_increment,identity_maximum,identity_minimum,identity_cycle,is_generated,generation_expression,is_updatable,COLUMN_COMMENT
0,exercise2,main,sales,transaction_id,1,None,YES,INTEGER,<NA>,<NA>,...,None,None,None,None,None,<NA>,None,None,<NA>,None
1,exercise2,main,sales,product_id,2,None,YES,INTEGER,<NA>,<NA>,...,None,None,None,None,None,<NA>,None,None,<NA>,None
2,exercise2,main,sales,sale_date,3,None,YES,DATE,<NA>,<NA>,...,None,None,None,None,None,<NA>,None,None,<NA>,None
3,exercise2,main,sales,quantity,4,None,YES,INTEGER,<NA>,<NA>,...,None,None,None,None,None,<NA>,None,None,<NA>,None
4,exercise2,main,sales,price,5,None,YES,DOUBLE,<NA>,<NA>,...,None,None,None,None,None,<NA>,None,None,<NA>,None
5,exercise2,main,sales,customer_id,6,None,YES,VARCHAR,<NA>,<NA>,...,None,None,None,None,None,<NA>,None,None,<NA>,None


Now let's do the same for PostgreSQL:

In [17]:
%sql postgresql://postgres:postgres@127.0.0.1:5432/postgres

In [18]:
%%sql
--- BEGIN SOLUTION
ALTER TABLE          
sales                
ADD COLUMN           
customer_id VARCHAR; 
--- END SOLUTION

""


Now let's query the PostgreSQL metadata to see the updated schema:

In [19]:
%%sql
SELECT column_name, data_type
FROM information_schema.columns
WHERE table_name = 'sales'
ORDER BY ordinal_position;

,column_name,data_type
0,transaction_id,integer
1,product_id,integer
2,sale_date,date
3,quantity,integer
4,price,numeric
5,customer_id,character varying


We can see clearly, how things have changed. We won't be using the customer_id in the future, so we can drop it for the sake of future demonstrations.

In [20]:
%sql duckdb:///exercise2.db

In [21]:
%%sql
ALTER TABLE 
sales 
DROP COLUMN 
customer_id;

,Success


In [22]:
%sql postgresql://postgres:postgres@127.0.0.1:5432/postgres

In [23]:
%%sql
ALTER TABLE 
sales 
DROP COLUMN 
customer_id;

""


**Key Observation:** Notice how the metadata systems in both DuckDB and PostgreSQL now reflect the new `customer_id` column. The metadata layer automatically tracked this schema change, ensuring that:

1. The query engine knows about the new column and its type (VARCHAR)
2. Future queries can reference this column
3. The schema is consistent and enforced across all operations

This demonstrates how metadata management is essential for maintaining data integrity and enabling proper database operations!

## Part 3: Externalizing Metadata with Parquet and Data Catalogs

Now we can really understand why metadata shines - we can actually remove it from the equation in this next step. What if we separate the metadata from the data and the query engine? This is the core idea behind modern data lakehouse architecture. Here, data is stored in an open format like Parquet or Avro, and metadata is stored in a catalog like Apache Iceberg. These are open source methods and standards for storing data, as well as managing its metadata. Parquet storage was originally based off of a paper on Dremel (the system behind Google BigQuery), and Avro was designed within the Apache Hadoop project. You can read more about them below. 

Parquet: https://parquet.apache.org/

Avro: https://avro.apache.org/

Iceberg: https://iceberg.apache.org/

All of these open source standards/projects are currently managed by the Apache Foundation.

Let's try using DuckDB's feature which allows us to read and write to files directly, bypassing the standard database storage that DuckDB comes built with.

In [24]:
%sql duckdb:///exercise2.db

In [25]:
%%sql
COPY sales TO 'sales_data.parquet' (FORMAT parquet);

,Success


Now, instead of a database managing everything, we have separate components:

First, we'll work with the storage layer: The sales_data.parquet file sitting in a folder or drive.

Let's query the Parquet files:

In [26]:
%%sql
SELECT * FROM 'sales_data.parquet';

,transaction_id,product_id,sale_date,quantity,price
0,1,101,2025-10-14,5,19.99
1,2,102,2025-10-14,1,250.00
2,3,101,2026-01-30,3,19.99
3,4,103,2026-03-15,10,5.50
4,5,102,2026-10-16,2,245.00
...,...,...,...,...,...
4050,1,101,2025-10-14,5,19.99
4051,2,102,2025-10-14,1,250.00
4052,3,101,2026-01-30,3,19.99
4053,4,103,2026-03-15,10,5.50


Note that this reads the file directly, and at first glance, everything appears as it was before. There is one catch though: suppose for example, we want to add to this file. We can do one of two things:

- Add a new file
- Re-write the existing file

Both are quite troublesome and involve some work. With the first option, this might be faster, but it misses out on benefits provided by compression across these two files. Some repeated values in the second file will be stored twice (in the first and the latter). 

What if we want to change the data type in the file? We would have to do the same thing again - once again we are faced with the same two options. 

What if we wanted to insert a row, or update an existing row? we run into the same issues once again. Not only do these problems arise, but we also run into a bigger challenge: ACID guarantees. We will come back to this later, but for now it is sufficient to understand that: if we want to read all the parquet or avro files in one folder, there is no real system that guarantees across all the writers to this folder, that the data types, columns, etc., have to be atomic, consistent, isolated, or durable. Without ACID guarantees, certain statements, such as INSERT, or UPDATE, don't really work. How can you insert data into a column, if you have no idea what type it is, for example? You would need some type of consistency guarantee. 

With this new, unrestricted process, files could be randomly deleted, in between the parquet or avro files we could have cat videos uploaded to that drive, or we could have random code scripts executing on the same file, making conflicting changes to it. This would be challenging to any software system we want to build, that should be robust (if you want to learn more about these issues, we highly recommend reading Designing Data Intensive Applications, a survey book on this topic).

In order to manage all of this, we need a system to store data about data - what we call metadata. Now that we're writing and reading directly to files instead of DuckDB's own internal storage system, we're going to miss all of this, and we'll need to substitute something for it - but first, let's see these scenarios at play in a live example.

### Demonstrating the Two Options for Adding Data

Let's demonstrate both approaches with code:

#### Option 1: Add a New Separate File

This is faster but loses compression benefits. Repeated values (like 19.99 and 245.00) will be stored in both files.

#### Task 6: Add the following records and then run the query to see newly inserted data.

| transaction_id | product_id | sale_date | quantity | price |
| :---: | :---: | :---: | :---: | :---: |
| 7 | 104 | 2026-11-15 | 2 | 99.99 |
| 8 | 102 | 2026-12-01 | 4 | 245.00 |

Note: you will have to fill in the areas that say -- YOUR CODE HERE - otherwise the positional query will have the engine skip to putting the next value into the earlier column. In this scenario, It will try to put 7 into a date column and this may result in errors

In [27]:
%%sql
COPY 
(
  SELECT
    6 as transaction_id, 
    101 as product_id,
    --- BEGIN SOLUTION 
    '2026-11-01' as sale_date,
    --- END SOLUTION
    7 as quantity, 
    19.99 as price
  UNION ALL
  SELECT 
    7, 
    104, 
    '2026-11-15', 
    2, 
    99.99
  UNION ALL
  SELECT 
    --- BEGIN SOLUTION
    8, 
    102,         
    '2026-12-01', 
    4, 
    245.00 
    --- END SOLUTION
)

TO 'sales_data_new.parquet' (FORMAT parquet);

,Success


Let's now see what the data looks like in terms of size:

In [28]:
# Check file sizes - repeated values stored in both files
import os

size_original = os.path.getsize('sales_data.parquet')
size_new = os.path.getsize('sales_data_new.parquet')

print(f"Original file size: {size_original} bytes")
print(f"New file size: {size_new} bytes")
print(f"Total storage (Option 1): {size_original + size_new} bytes")
print(f"\nNote: Values like 19.99 and 245.00 appear in both files,")
print("reducing compression efficiency across the dataset.")


Original file size: 1757 bytes
New file size: 745 bytes
Total storage (Option 1): 2502 bytes

Note: Values like 19.99 and 245.00 appear in both files,
reducing compression efficiency across the dataset.


Let's take a look at what both files look like when we read them together:

In [29]:
%%sql
SELECT * FROM 'sales_data.parquet'
UNION ALL
SELECT * FROM 'sales_data_new.parquet'
ORDER BY transaction_id;

,transaction_id,product_id,sale_date,quantity,price
0,1,101,2025-10-14,5,19.99
1,1,101,2025-10-14,5,19.99
2,1,101,2025-10-14,5,19.99
3,1,101,2025-10-14,5,19.99
4,1,101,2025-10-14,5,19.99
...,...,...,...,...,...
4053,5,102,2026-10-16,2,245.00
4054,5,102,2026-10-16,2,245.00
4055,6,101,2026-11-01,7,19.99
4056,7,104,2026-11-15,2,99.99


#### Option 2: Re-write the Existing File

This takes more time because we must read all old data, combine it with new data, and write everything back. However, it allows better compression since all repeated values are in one file. Once again, add the following data to the query to put it all into one file:

#### Task 7: Add the following records and then run the query to see newly inserted data.

| transaction_id | product_id | sale_date | quantity | price |
| :---: | :---: | :---: | :---: | :---: |
| 7 | 104 | 2026-11-15 | 2 | 99.99 |
| 8 | 102 | 2026-12-01 | 4 | 245.00 |

In [ ]:
%%timeit -n 1 -r 1
%%sql
COPY (
    SELECT transaction_id, product_id, sale_date, quantity, price FROM 'sales_data.parquet'
    UNION ALL
      SELECT 6 as transaction_id, 
        101 as product_id, 
        '2026-11-01' as sale_date, 
        7 as quantity, 
        19.99 as price
    UNION ALL
      SELECT 
        7, 
        104, 
        '2026-11-15',
        2, 
        --- BEGIN SOLUTION
        99.99 
        --- END SOLUTION
    UNION ALL
      SELECT 
        --- BEGIN SOLUTION
        8, 
        102,          
        '2026-12-01', 
        4, 
        245.00 
        --- END SOLUTION
    ORDER BY transaction_id
)
TO 'sales_data_combined.parquet' (FORMAT parquet);

22.7 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)


Once again, let's take a look at the combined file and the file size:

In [31]:
# Compare storage efficiency
size_combined = os.path.getsize('sales_data_combined.parquet')

print(f"Combined file size (Option 2): {size_combined} bytes")
print(f"Total storage (Option 1): {size_original + size_new} bytes")
print(f"\nCompression savings: {(size_original + size_new) - size_combined} bytes")
print(f"Efficiency gain: {((size_original + size_new - size_combined) / (size_original + size_new)) * 100:.1f}%")
print(f"\nOption 2 benefits from better compression as repeated values")
print("(like 19.99, 245.00, product_ids 101 & 102) are stored once in the dictionary.")

Combined file size (Option 2): 1343 bytes
Total storage (Option 1): 2502 bytes

Compression savings: 1159 bytes
Efficiency gain: 46.3%

Option 2 benefits from better compression as repeated values
(like 19.99, 245.00, product_ids 101 & 102) are stored once in the dictionary.


In [32]:
%%sql
SELECT * FROM 'sales_data_combined.parquet';

,transaction_id,product_id,sale_date,quantity,price
0,1,101,2025-10-14,5,19.99
1,1,101,2025-10-14,5,19.99
2,1,101,2025-10-14,5,19.99
3,1,101,2025-10-14,5,19.99
4,1,101,2025-10-14,5,19.99
...,...,...,...,...,...
4053,5,102,2026-10-16,2,245.00
4054,5,102,2026-10-16,2,245.00
4055,6,101,2026-11-01,7,19.99
4056,7,104,2026-11-15,2,99.99


#### Comparison Summary

In short, you can see how option 2 saves on space, but involves more write time, and option 1 saves on write time, but loses compression. Both options have pros and cons:

**Option 1 (Add new file):**
- ✓ Faster write operation
- ✗ Less efficient storage (repeated values stored multiple times)
- ✗ Need to query multiple files
- ✗ More complex data management

**Option 2 (Re-write combined file):**
- ✗ Slower write operation (must read + write all data)
- ✓ Better compression efficiency
- ✓ Single file to query
- ✓ Simpler data management

However, as we will see, with metadata management, these tradeoffs go away. This illustrates why metadata management systems are valuable—they handle these challenges automatically while providing ACID guarantees - so we don't have to deal with this!



### Introducing Errors: What Happens Without Metadata Management?

Now let's see what can go wrong when we don't have a proper metadata system managing our files:

In [33]:
%%sql
-- Let's create a new parquet file with DIFFERENT schema - wrong data types!
COPY (
    SELECT 
        '006' as transaction_id,  -- STRING instead of INTEGER!
        101 as product_id, 
        '2026-11-20' as sale_date, 
        3 as quantity, 
        'NINETEEN DOLLARS' as price  -- STRING instead of DOUBLE!
)
TO 'sales_data_broken.parquet' (FORMAT parquet);

,Success


Now, let's try to query all three files together. Without metadata management, there's no system preventing us from mixing incompatible schemas:

In [34]:
%%sql
SELECT * FROM 'sales_data.parquet'
UNION ALL
SELECT * FROM 'sales_data_new.parquet'
UNION ALL
SELECT * FROM 'sales_data_broken.parquet';


,transaction_id,product_id,sale_date,quantity,price
0,1,101,2025-10-14,5,19.99
1,2,102,2025-10-14,1,250.0
2,3,101,2026-01-30,3,19.99
3,4,103,2026-03-15,10,5.5
4,5,102,2026-10-16,2,245.0
...,...,...,...,...,...
4054,5,102,2026-10-16,2,245.0
4055,6,101,2026-11-01,7,19.99
4056,7,104,2026-11-15,2,99.99
4057,8,102,2026-12-01,4,245.0


While the query actually returned a result, this is dangerous! Let's try an operation, such as calculating the average price.

#### Task 8: Calculate the average price across the files.

In [35]:
%%sql
SELECT 
--- BEGIN SOLUTION
AVG(price) as average_price
--- END SOLUTION
FROM (
SELECT * FROM 'sales_data.parquet'
UNION ALL
SELECT * FROM 'sales_data_new.parquet'
UNION ALL
SELECT * FROM 'sales_data_broken.parquet');


RuntimeError: (_duckdb.BinderException) Binder Error: No function matches the given name and argument types 'avg(VARCHAR)'. You might need to add explicit type casts.
	Candidate functions:
	avg(DECIMAL) -> DECIMAL
	avg(SMALLINT) -> DOUBLE
	avg(INTEGER) -> DOUBLE
	avg(BIGINT) -> DOUBLE
	avg(HUGEINT) -> DOUBLE
	avg(INTERVAL) -> INTERVAL
	avg(DOUBLE) -> DOUBLE
	avg(TIMESTAMP) -> TIMESTAMP
	avg(TIMESTAMP WITH TIME ZONE) -> TIMESTAMP WITH TIME ZONE
	avg(TIME) -> TIME
	avg(TIME WITH TIME ZONE) -> TIME WITH TIME ZONE


LINE 3: AVG(price) as average_price
        ^
[SQL: SELECT

AVG(price) as average_price

FROM (
SELECT * FROM 'sales_data.parquet'
UNION ALL
SELECT * FROM 'sales_data_new.parquet'
UNION ALL
SELECT * FROM 'sales_data_broken.parquet');]
(Background on this error at: https://sqlalche.me/e/20/f405)


**Expected Error:** You'll get a type mismatch error because:
- `transaction_id` is INTEGER in the first two files but VARCHAR in the broken file
- `price` is DOUBLE in the first two files but VARCHAR in the broken file

**Why This is a Problem:**
1. **No Schema Enforcement**: Without metadata management, anyone can write files with different schemas to the same directory
2. **Runtime Errors**: Errors only appear when querying, not when writing
3. **Data Corruption Risk**: Mixed data types can lead to incorrect results or data loss
4. **No ACID Guarantees**: Multiple processes could be writing conflicting data simultaneously

This is exactly why metadata and ACID guarantees are so important!

### Introducing External Metadata Management: 

In addition to PostgreSQL or DuckDB's own internal systems, another option that is particularly popular, is Apache Iceberg. In this example when we wrote directly to Parquet and ran into schema/compression/file issues, Iceberg can help us!

Apache Iceberg is an open table format designed for large analytic datasets in data lakes. It's not a storage system or a query engine; instead, it's a specification that defines how to manage the files that make up a large table. Think of it as a sophisticated index or "table of contents" for your data files (like Parquet or ORC) sitting in cloud storage like Amazon S3. Iceberg allows different query engines like Spark, Trino, and Flink to work with the same data reliably and efficiently. It also enables them to use certain statements that require ACID guarantees such as INSERT, or UPDATE. Basically, instead of a database managing your metadata for you, Iceberg can handle that - including keeping information about data types, columns, and so on. 

Now, we'll setup Apache Iceberg in the next steps:

In [36]:

WAREHOUSE_DIR = "iceberg_catalog"
CATALOG_DB_PATH = f"{WAREHOUSE_DIR}/catalog.db"
NAMESPACE = "dev_sales"
TABLE_IDENTIFIER = f"{NAMESPACE}.daily_summary"
os.makedirs(WAREHOUSE_DIR, exist_ok=True)

# 1. Load the PyIceberg Catalog (using SQLite for metadata)
catalog = load_catalog(
    "default",
    type="sql",
    uri=f"sqlite:///{CATALOG_DB_PATH}",
    warehouse=f"file://{WAREHOUSE_DIR}",
)

In [37]:
# 1. Create a Namespace (database) using the Python API
catalog.create_namespace_if_not_exists(NAMESPACE)

# 2. Create the Iceberg Table
iceberg_schema = Schema(
    NestedField(field_id=1, name="transaction_id", field_type=IntegerType(), required=True),
    NestedField(field_id=2, name="product_id", field_type=IntegerType(), required=True),
    NestedField(field_id=3, name="quantity", field_type=IntegerType(), required=True),
    NestedField(field_id=4, name="price", field_type=FloatType(), required=True),
)

table = catalog.create_table_if_not_exists(
    identifier=TABLE_IDENTIFIER,
    schema=iceberg_schema,
)
print(f"\nIceberg Table created: {TABLE_IDENTIFIER}")


Iceberg Table created: dev_sales.daily_summary


In [38]:
# 3. Prepare Sample Data
data = pd.DataFrame({
    'transaction_id': [1, 2, 3, 4, 5],
    'product_id': [101, 102, 101, 103, 102],
    'quantity': [5, 1, 3, 10, 2],
    'price': [19.99, 250.00, 19.99, 5.50, 245.00]
})

data = data.astype({
    'transaction_id': 'int32',
    'product_id': 'int32',
    'quantity': 'int32',
    'price': 'float32'
})

arrow_schema = iceberg_schema.as_arrow()

arrow_table = pa.Table.from_pandas(data, schema=arrow_schema, preserve_index=False)

# 4. Append Data using PyIceberg API
table.append(arrow_table)
print("Data successfully appended to the Iceberg table via PyIceberg.")

Data successfully appended to the Iceberg table via PyIceberg.


Next, let's query the table - this time, we won't even use DuckDB, we'll just use PyIceberg to do a straight read right into Pandas, a totally different Python library for querying and working with data.  

In [39]:
print("\n--- PyIceberg API Full Scan Results (as Pandas) ---")
df_full_scan = table.scan().to_pandas()
print(df_full_scan)


--- PyIceberg API Full Scan Results (as Pandas) ---
   transaction_id  product_id  quantity   price
0               1         101         5   19.99
1               2         102         1  250.00
2               3         101         3   19.99
3               4         103        10    5.50
4               5         102         2  245.00
5               1         101         5   19.99
6               2         102         1  250.00
7               3         101         3   19.99
8               4         103        10    5.50
9               5         102         2  245.00


See how this allows us to use ACID statements, and allows different query engines to access the same table. Pretty neat right? This also guards us from making type errors, prevents uploading of random files into the db folder, and so on, which was the issue previously when we wrote directly to the parquet file. There are other benefits as well, which we will review next class as we learn more about ACID. For example, using a catalog for some query engines enables speedups: to find the right data, query engines must perform slow and expensive "list directory" operations on thousands or millions of files and folders especially in cloud storage to see where each piece of data lives. But Iceberg stores all that metadata for the query engine, so it's not necessary if you're using a metadata system.

### Part 4: The Bring Your Own "Universe" 

So now, we have a "Bring your own Query Engine" sort of setup. We also have a "Bring your own Data Storage Format" setup, while Apache Iceberg manages metadata. 

Overall, we've used:

- Metadata Layer (Catalog): An Apache Iceberg or DuckLake catalog that stores metadata: the file path, table schema (column names/types), and statistics (e.g., min/max values in a column).
- Query Engine: A tool like DuckDB, Spark, or Trino that reads the metadata from the catalog to find the right data files and then executes the query.
- Storage Format: In our case, column store Parquet format, so that we can read quickly and aggregate at speed. 

What's left? What if there were other metadata storage formats?! And in fact, DuckDB comes with two - it's own internal system, which you can choose to use and completely ignore metadata management - or DuckLake!

#### DuckLake
This system is sort of like Iceberg. It manages metadata for you. However, unlike Iceberg, which stores metadata in specific files (and it does this the same way every time), DuckLake allows you to store metadata in *many* different systems. That includes regular files, or SQLite files, or PostgreSQL - where metadata is stored as records in a metadata PostgreSQL table itself! Even MySQL is an option. Essentially, you can think of Ducklake as DuckDB - but instead of storing data in the typical DuckDB database format, it allows you to store data in files such as Parquet, and metadata in many other systems! 

Read more about DuckLake here: https://ducklake.select/

In [40]:
%%sql
INSTALL ducklake;

,Success


#### DuckLake with File Metadata:

In [41]:
%%sql
ATTACH 'ducklake:metadata.ducklake' AS my_ducklake;
USE my_ducklake;

,Success


#### DuckLake with PostgreSQL Metadata:

In [42]:
%%sql
INSTALL postgres;
ATTACH 'ducklake:postgres:dbname=postgres user=postgres password=postgres host=127.0.0.1' AS my_ducklake_postgres
     (DATA_PATH 'data_files/');
USE my_ducklake_postgres;

,Success


Immediately after attaching the database, you can create tables! Unlike the first time we created tables with DuckDB's internal system, this time the data is stored as files, but metadata is stored in Postgres. 

In [43]:
%%sql
DROP TABLE IF EXISTS TESTING_DUCKLAKE;
CREATE TABLE TESTING_DUCKLAKE (
    ID INTEGER,
    TESTING VARCHAR,
    TESTING_LAUNCH_DATE DATE
);

,Success


#### Task 9: Let's query the metadata information table in PostgreSQL, that was stored there by DuckLake! Select table_name, and table_schema columns.


In [44]:
%sql postgresql://postgres:postgres@127.0.0.1:5432/postgres

In [45]:
%%sql
-- Query the DuckLake metadata tables stored in PostgreSQL
SELECT 
--- BEGIN SOLUTION
 table_name,  
 table_schema 
--- END SOLUTION
FROM information_schema.tables
WHERE table_schema = 'ducklake_catalog' OR table_name LIKE '%ducklake%'
ORDER BY table_schema, table_name;

,table_name,table_schema
0,ducklake_column,public
1,ducklake_column_mapping,public
2,ducklake_column_tag,public
3,ducklake_data_file,public
4,ducklake_delete_file,public
5,ducklake_file_column_stats,public
6,ducklake_file_partition_value,public
7,ducklake_files_scheduled_for_deletion,public
8,ducklake_inlined_data_tables,public
9,ducklake_metadata,public


At this point, you can practically bring your own universe when it comes to data tools! Whatever query engine you need for your use case, whatever data storage format, and so on. The flexibility with the modern "Lake House" structure (often what this is referred to in practice) is unbeatable.

You may want to use this sort of setup, if you're more interested in integrating different tools and sources, instead of going with a one-size-fits-all approach (i.e. a single database) to your data infrastructure. 


| type | DuckLake | Iceberg |
| - | - | - |
data options | Avro, Parquet, etc. | Avro, Parquet, etc. |
metadata options |Files, PostgreSQL, MySQL | Files |


### Stand Out!
Task (Thought Exercise):

- What is the main advantage of decoupling storage, metadata, and query engine? (Hint: Think about flexibility).
- If you wanted to update the data type of the price column from FLOAT to DECIMAL(10, 2), which component(s) would you need to interact with in this new, decoupled system?


The most interesting part of this is that you can choose your query engine and your data storage to fit your needs. This means, you can use Spark, or Polars, or DuckDB - the latter allows you to run DuckLake, which instead of running DuckDB as a database, allows you to choose your storage format etc. etc. avoid lock in plug and play, customization, etc.